server:
  port: 9101

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  cloud:
    sentinel:
      eager: true
      log:
        dir: ${SENTINEL_LOG_DIR:./logs/sentinel}

feign:
  sentinel:
    enabled: true

jwt:
  secret: abc123456abc123456abc123456abc123456
  expire: 7200

springdoc:
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.system.auth.controller

management:
  endpoints:
    web:
      exposure:
        include: health,sentinel
  endpoint:
    health:
      show-details: never
