spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      datasource:
        degrade-rules:
          nacos:
            server-addr: 127.0.0.1:8848
            data-id: auth-service-sentinel-degrade-rules.json
            group-id: DEFAULT_GROUP
            rule-type: degrade
            data-type: json
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    root: info
    com.system.auth: debug
