spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
    sentinel:
      datasource:
        degrade-rules:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
            data-id: ${SENTINEL_AUTH_DEGRADE_DATA_ID:auth-service-sentinel-degrade-rules.json}
            group-id: ${SENTINEL_RULE_GROUP:DEFAULT_GROUP}
            rule-type: degrade
            data-type: json
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:abc123456abc123456abc123456abc123456}
  expire: ${JWT_EXPIRE:7200}

springdoc:
  api-docs:
    enabled: false

logging:
  level:
    root: warn
    com.system.auth: info
