spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    root: info
    com.system.auth: debug
