spring:
  config:
    import:
      - optional:nacos:gateway-service-prod.yaml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
        file-extension: yaml
        group: DEFAULT_GROUP

knife4j:
  gateway:
    enabled: false

logging:
  level:
    root: warn
    com.system.gateway: info
