spring:
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        enabled: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    root: info
    com.system.gateway: info
