spring:
  config:
    import:
      - optional:nacos:gateway-service-prod.yaml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
        file-extension: yaml
        group: DEFAULT_GROUP

knife4j:
  gateway:
    enabled: false

management:
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.1}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}

logging:
  level:
    root: warn
    com.system.gateway: info
