server:
  port: 9401

spring:
  application:
    name: file-service
  profiles:
    active: dev
  cloud:
    sentinel:
      eager: true
      log:
        dir: ${SENTINEL_LOG_DIR:./logs/sentinel}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

feign:
  sentinel:
    enabled: true

file:
  storage:
    upload-path: ./upload

springdoc:
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.system.controller

management:
  endpoints:
    web:
      exposure:
        include: health,sentinel
  endpoint:
    health:
      show-details: never
