spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/admin_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: ${DB_PWD:123456}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PWD:guest}

file:
  storage:
    upload-path: /app/upload

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

logging:
  level:
    root: info
    com.system: info
